.rules: &rules
  - if: "$CI_COMMIT_TAG"
    when: manual
    allow_failure: true
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_PIPELINE_SOURCE == "web"

.rules_manual: &rules_manual
  - if: "$CI_COMMIT_TAG"
    when: manual
    allow_failure: true
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    when: manual
    allow_failure: true
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: manual
    allow_failure: true
  - if: $CI_PIPELINE_SOURCE == "web"
    when: manual
    allow_failure: true

stages:
  - .pre
  - build
  - test
  - pack
  - publish
  - deploy
  - release
  - release-public

include:
  - project: 'vicione-oss/tooling/templates'
    file: '/CI-Templates/v2/dotnet.yml'
  - project: 'vicione-oss/tooling/ci-templates'
    file: '/project/v1/dotnet.yml'
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-restore@2.2.0
    inputs:
      rules: *rules
      before_script:
        - dotnet nuget update source JFrogNuGetProxy --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
        - dotnet nuget update source JFrogViciOne --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-build@2.2.0
    inputs:
      rules: *rules
      before_script:
        # Aspire.AppHost.Sdk gets restored during build and not during restore
        - dotnet nuget update source JFrogNuGetProxy --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-test@2.2.0
    inputs:
      rules: *rules
      before_script:
        # necessary to be able to pass tests in PackageResolvers.NuGet.Tests
        - dotnet nuget update source JFrogNuGetProxy --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
        - dotnet nuget remove source JFrogViciOne
      coverage: true
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-pack@2.1.1
    inputs:
      rules: *rules_manual
      before_script:
        # Aspire.AppHost.Sdk gets restored during build and not during restore
        - dotnet nuget update source JFrogNuGetProxy --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-nuget-push@2.1.1
    inputs:
      rules: *rules_manual
      source: 'JFrogViciOne'
      before_script:
       - dotnet nuget update source JFrogViciOne --configfile NuGet.Config -u $NuGet_User_RW_JFrog -p $NuGet_PW_RW_JFrog --store-password-in-clear-text

default:
  image: mcr.microsoft.com/dotnet/sdk:10.0

markdown:
  extends: .dotnet-test-xunit
  variables: null
  artifacts: null
  image:
    name: davidanson/markdownlint-cli2:v0.20.0
    entrypoint: ["/bin/sh", "-c"]
  script:
    - markdownlint-cli2 "${CI_PROJECT_DIR}/**/*.md" "!${CI_PROJECT_DIR}/packages"

Prerelease EngineHost Raw:
  extends: .dotnet-deploy-raw-rids
  variables:
    SERVER: 'https://ifm.jfrog.io/artifactory/vicione-suite-dev'
    USER: ${Raw_User_RW_JFrog}
    PASSWORD: ${Raw_PW_RW_JFrog}
    PROJECT: 'src/EngineHost/EngineHost.csproj'
    DST_DIRECTORY: 'enginehost'
    SELF_CONTAINED: 'true'
    METADATA_FILE: 'src/EngineHost/metadata.json'
    METADATA_VERSION_FILE: 'VERSION'
    METADATA_MIN_VERSION_FILE: 'VERSION_CORE'
    METADATA_MIN_VERSION_KEY: 'MinCoreVersion'
  after_script:
    - !reference [.push-metadata]

Release EngineHost Raw:
  extends: .dotnet-release-raw-rids
  variables:
    SERVER: 'https://ifm.jfrog.io/artifactory/vicione-suite-staging'
    USER: ${Raw_User_RW_JFrog}
    PASSWORD: ${Raw_PW_RW_JFrog}
    PROJECT: 'src/EngineHost/EngineHost.csproj'
    DST_DIRECTORY: 'enginehost'
    SELF_CONTAINED: 'true'
    METADATA_FILE: 'src/EngineHost/metadata.json'
    METADATA_VERSION_FILE: 'VERSION'
    METADATA_MIN_VERSION_FILE: 'VERSION_CORE'
    METADATA_MIN_VERSION_KEY: 'MinCoreVersion'
  after_script:
    - !reference [.push-metadata]

Public Release Raw:
  extends: .dotnet-release-public

.release_job: &release_job
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_REF_PROTECTED == "true"

.git_version: &git_version
  image:
    name: gittools/gitversion:6.5.1-alpine.3.22-10.0
    entrypoint: [""]
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 0

Get version:
  stage: .pre
  <<: *git_version
  script:
    - |
      Version=$(/tools/dotnet-gitversion /output json /showvariable SemVer)
      echo "VERSION=${Version}" > version.env
      echo "PACKAGEVERSION=${Version}" > version.env
  artifacts:
    reports:
      dotenv: version.env

# https://docs.gitlab.com/ee/user/project/releases/release_cicd_examples.html#create-release-metadata-in-a-custom-script
Get next version:
  <<: *release_job
  when: manual
  dependencies: [] # Does not need any artifacts of previous stages
  <<: *git_version
  script:
    - |
      NextVersion=$(/tools/dotnet-gitversion /output json /showvariable MajorMinorPatch)
      echo "NEXTVERSION=${NextVersion}" > nextversion.env
    - |
      echo -e "🚩"
      echo -e "🚩 Version for next release \e[31m${NextVersion}\e[0m 🚀"
      echo -e "🚩"
  artifacts:
    reports:
      dotenv: nextversion.env

Confirm next version:
  <<: *release_job
  when: manual
  manual_confirmation: "Are you sure you want to create a release with the version found in the previous job? If not, run the job with a custom value for variable Version."
  needs:
    - job: Get next version
  variables:
    Version: $NEXTVERSION
  script:
    - echo "NEXTVERSION=${Version}" > nextversion.env
  artifacts:
    reports:
      dotenv: nextversion.env

Get changelog:
  <<: *release_job
  needs:
    - job: Confirm next version
  script:
    - sed "0,/^## ${NEXTVERSION}/d;/^## /Q" CHANGELOG.md | sed '1d;$d' > changelog.md
  artifacts:
    expire_in: 1 week
    paths:
      - changelog.md

Create release:
  <<: *release_job
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: Confirm next version
    - job: Get changelog
  # https://docs.gitlab.com/ee/ci/yaml/index.html#release
  script:
    - echo "" # unfortunately mandatory and addressed in https://gitlab.com/gitlab-org/gitlab/-/issues/223856
  release:
    tag_name: 'v$NEXTVERSION'
    tag_message: 'Version $NEXTVERSION'
    name: 'v$NEXTVERSION'
    description: './changelog.md'
