.rule_tag: &rule_tag
  if: "$CI_COMMIT_TAG"

.rule_tag_manual: &rule_tag_manual
  <<: *rule_tag
  when: manual
  allow_failure: true

.rule_default_branch: &rule_default_branch
  if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

.rule_default_branch_manual: &rule_default_branch_manual
  <<: *rule_default_branch
  when: manual
  allow_failure: true

.rule_mr: &rule_mr
  if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

.rule_mr_manual: &rule_mr_manual
  <<: *rule_mr
  when: manual
  allow_failure: true

.rule_web: &rule_web
  if: '$CI_PIPELINE_SOURCE == "web"'

.rule_web_manual: &rule_web_manual
  <<: *rule_web
  when: manual
  allow_failure: true

.rules_always: &rules_always
  - *rule_tag
  - *rule_default_branch
  - *rule_mr
  - *rule_web

.rules_manual: &rules_manual
  - *rule_tag_manual
  - *rule_default_branch_manual
  - *rule_mr_manual
  - *rule_web_manual

.rules_only_tags: &rules_only_tags
  - *rule_tag

.rules_not_tags: &rules_not_tags
  - *rule_default_branch
  - *rule_mr
  - *rule_web

.rules_only_tags_manual: &rules_only_tags_manual
  - *rule_tag_manual

.rules_not_tags_manual: &rules_not_tags_manual
  - *rule_default_branch_manual
  - *rule_mr_manual
  - *rule_web_manual

.rules_tags_else_manual: &rules_tags_else_manual
  - *rule_tag
  - *rule_default_branch_manual
  - *rule_mr_manual
  - *rule_web_manual

.update_nuget_source_ro: &update_nuget_source_ro
  - dotnet nuget update source JFrogNuGetProxy --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
  - dotnet nuget update source JFrogViciOne --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text

# Aspire.AppHost.Sdk gets restored during build and not during restore
.update_nuget_proxy_ro: &update_nuget_proxy_ro
  - dotnet nuget update source JFrogNuGetProxy --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text

variables:
  IMAGE_NAME: mcr.microsoft.com/dotnet/sdk:10.0.103
  PROJECT_FULLNAME: "enginehost"

stages:
  - build
  - test
  - pack
  - publish
  - release

include:
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/components/module-packaging/runtime-identifier@v0.2.0
    inputs:
      rules: *rules_always
      project: "src/EngineHost/EngineHost.csproj"
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-restore@v2.7.1
    inputs:
      image: ${IMAGE_NAME}
      rules: *rules_always
      before_script:
        - *update_nuget_source_ro
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/components/module-packaging/metadata@v0.2.0
    inputs:
      name: "Project Metadata"
      stage: build
      rules: *rules_always
      project: "src/EngineHost/EngineHost.csproj"
      module_version: "${VERSION}"
      metadata_json: "src/EngineHost/metadata.json"
      min_core_version_file: "VERSION_CORE"
      min_core_version_property: "MinCoreVersion"
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-build@v2.7.1
    inputs:
      image: ${IMAGE_NAME}
      rules: *rules_only_tags
      before_script:
        - *update_nuget_proxy_ro
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-artifacts@v2.7.1
    inputs:
      image: ${IMAGE_NAME}
      name: "Build+Test"
      stage: test
      rules: *rules_not_tags
      before_script:
        # necessary to be able to pass tests in PackageResolvers.NuGet.Tests
        - *update_nuget_source_ro
      build: true
      test: true
      test_coverage: true
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-pack@v2.7.1
    inputs:
      image: ${IMAGE_NAME}
      name: "Pack NuGets"
      rules: *rules_tags_else_manual
      before_script:
        - *update_nuget_proxy_ro
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-nuget-push@v2.7.1
    inputs:
      image: ${IMAGE_NAME}
      name: "Push NuGets"
      stage: publish
      rules: *rules_manual
      pack_job_name: "Pack NuGets"
      before_script:
        - dotnet nuget update source JFrogViciOne --configfile NuGet.Config -u $NuGet_User_RW_JFrog -p $NuGet_PW_RW_JFrog --store-password-in-clear-text
        - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name GitLabRegistry --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
      sources:
        - "JFrogViciOne"
        - "GitLabRegistry"
  # Publish RIDs
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-publish@v2.7.1
    inputs:
      image: ${IMAGE_NAME}
      stage: pack
      rules: *rules_tags_else_manual
      project: "src/EngineHost/EngineHost.csproj"
      self_contained: true
      output_directory: "artifacts/${OS}-${ARCH}"
      before_script:
        - *update_nuget_source_ro
        - dotnet restore
      execution_matrix:
        - OS: linux
          ARCH: [x64, arm64]
        - OS: win
          ARCH: [x64]
  # Pack binaries
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/components/module-packaging/package-module@v0.2.0
    inputs:
      name: "Pack binaries"
      stage: pack
      rules: *rules_always
      publish_job: "dotnet Publish"
      metadata_job: "Project Metadata"
      build_dir: "artifacts"
      before_script:
        - apt update
        - apt install jq zip -y
  # Prerelease binaries to dev repository
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/components/jfrog/release@v2.0.1
    inputs:
      name: "Push binaries (dev)"
      stage: publish
      rules: *rules_not_tags_manual
      repository: "vicione-suite-dev"
      upload_path: "${PROJECT_FULLNAME}"
      needs:
        - "Project Metadata"
        - "Pack binaries"
      artifacts:
        - "artifacts/**/*json"
        - "artifacts/**/*zip"
  # Release binaries to staging repository (on tag)
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/components/jfrog/release@v2.0.1
    inputs:
      name: "Push binaries (staging)"
      stage: publish
      rules: *rules_only_tags_manual
      repository: "vicione-suite-staging"
      upload_path: "${PROJECT_FULLNAME}"
      needs:
        - "Project Metadata"
        - "Pack binaries"
      artifacts:
        - "artifacts/**/*json"
        - "artifacts/**/*zip"
  # Promote staging to production (on tag)
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/components/jfrog/promote@v2.0.1
    inputs:
      name: "Release binaries"
      stage: release
      rules: *rules_only_tags_manual
      source_repository: "vicione-suite-staging"
      destination_repository: "vicione-suite"
      remote_path: "${PROJECT_FULLNAME}"

Lint Markdown:
  stage: test
  needs: []
  rules: *rules_not_tags
  image:
    name: davidanson/markdownlint-cli2:v0.20.0
    entrypoint: ["/bin/sh", "-c"]
  script:
    - markdownlint-cli2 "${CI_PROJECT_DIR}/**/*.md" "!${CI_PROJECT_DIR}/packages"

.release_job: &release_job
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_REF_PROTECTED == "true"

.git_version: &git_version
  image:
    name: gittools/gitversion:6.5.1-alpine.3.22-10.0
    entrypoint: [""]
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 0

Get version:
  stage: .pre
  rules: *rules_always
  <<: *git_version
  script:
    - |
      SemVer=$(/tools/dotnet-gitversion /output json /showvariable SemVer)
      echo "VERSION=${SemVer}" > version.env
      echo "PACKAGEVERSION=${SemVer}" >> version.env
      cat version.env
  artifacts:
    reports:
      dotenv: version.env

# https://docs.gitlab.com/ee/user/project/releases/release_cicd_examples.html#create-release-metadata-in-a-custom-script
Get next version:
  <<: *release_job
  when: manual
  dependencies: [] # Does not need any artifacts of previous stages
  <<: *git_version
  script:
    - |
      NextVersion=$(/tools/dotnet-gitversion /output json /showvariable MajorMinorPatch)
      echo "NEXTVERSION=${NextVersion}" > nextversion.env
    - |
      echo -e "🚩"
      echo -e "🚩 Version for next release \e[31m${NextVersion}\e[0m 🚀"
      echo -e "🚩"
  artifacts:
    reports:
      dotenv: nextversion.env

Confirm next version:
  <<: *release_job
  when: manual
  manual_confirmation: "Are you sure you want to create a release with the version found in `Get next version`? If not, change the input `Version`."
  needs:
    - Get next version
  inputs:
    Version:
      default: "0.0.0-default.change-if-required" # This value is never used, but GitLab requires a default value for manual inputs
      description: "Version to release (default: value from `Get next version`)"
      regex: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
  script:
    - VERSION=${{ job.inputs.Version }}
    - if [ "$VERSION" = "0.0.0-default.change-if-required" ]; then VERSION=$NEXTVERSION; fi
    - echo "NEXTVERSION=${VERSION}" > nextversion.env
  artifacts:
    reports:
      dotenv: nextversion.env

Get changelog:
  <<: *release_job
  needs:
    - Confirm next version
  script:
    - sed "0,/^## ${NEXTVERSION}/d;/^## /Q" CHANGELOG.md | sed '1d;$d' > changelog.md
  artifacts:
    expire_in: 1 week
    paths:
      - changelog.md

Create release:
  <<: *release_job
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - Confirm next version
    - Get changelog
  # https://docs.gitlab.com/ee/ci/yaml/index.html#release
  script:
    - echo "" # unfortunately mandatory and addressed in https://gitlab.com/gitlab-org/gitlab/-/issues/223856
  release:
    tag_name: 'v$NEXTVERSION'
    tag_message: 'Version $NEXTVERSION'
    name: 'v$NEXTVERSION'
    description: './changelog.md'
