<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Properties for all projects in the repo -->
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <!-- General information -->
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers Condition="$(MSBuildProjectDirectory.Contains('src'))">linux-x64;linux-arm64;win-x64</RuntimeIdentifiers>
    <Description>-</Description>
    <Product>ViciOne</Product>
    <Company>ifm software</Company>
    <Year>$([System.DateTime]::Now.Year)</Year>
    <Copyright>Copyright © $(Company) $(Year)</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
    <!-- Code quality -->
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile> <!-- Required for EnforceCodeStyleInBuild and NuGet packages -->
    <!-- NuGet lock file -->
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(CI)' == 'true'">true</RestoreLockedMode>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <DisableImplicitLibraryPacksFolder>true</DisableImplicitLibraryPacksFolder>
  </PropertyGroup>

  <!-- NuGet packages publish information -->
  <PropertyGroup>
    <!-- https://docs.microsoft.com/de-de/nuget/reference/msbuild-targets -->
    <PackageProjectUrl>https://gitlab.com/vicione-oss/vicione/runtime/engine-host</PackageProjectUrl>
    <Authors>$(Company)</Authors>
  </PropertyGroup>

  <!-- Properties for source projects -->
  <ItemGroup Condition="$(MSBuildProjectDirectory.Contains('src'))">
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" /> <!-- NSubstitute -->
  </ItemGroup>
  <PropertyGroup Condition="$(MSBuildProjectDirectory.Contains('src'))">
    <!-- IsPackable is individually enabled per project -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <!-- Properties for test projects -->
  <PropertyGroup Condition="$(MSBuildProjectDirectory.Contains('tests'))">
    <NoWarn>CS1591</NoWarn> <!-- Suppress documentation of public API -->
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsPublishable>true</IsPublishable>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner> <!-- Microsoft Testing Platform command line experience -->
  </PropertyGroup>

  <!-- Properties for sample projects -->
  <PropertyGroup Condition="$(MSBuildProjectDirectory.Contains('samples'))">
    <NoWarn>CS1591</NoWarn> <!-- Suppress documentation of public API -->
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>
</Project>
