<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>545af734-6880-4874-a133-00e736d4eee9</UserSecretsId>
    <!-- https://github.com/dotnet/aspire/issues/6184 -->
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <RestoreLockedMode>false</RestoreLockedMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EngineHost\EngineHost.csproj" />
    <ProjectReference Include="..\Aspire.Hosting.Mosquitto\Aspire.Hosting.Mosquitto.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
