<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet.Extensions" />
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="MQTTnet.Server" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CommunicationProviders\CommunicationProviders.csproj" />
  </ItemGroup>

</Project>
