<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <AssemblyName>ViciOne.ManagedEngine.Host</AssemblyName>
    <RootNamespace>ViciOne.ManagedEngine</RootNamespace>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\CommunicationProviders\Disposable.cs" Link="Disposable.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console">
      <TreatAsUsed>true</TreatAsUsed> <!-- Is used in appsettings.json to log to console -->
    </PackageReference>
    <PackageReference Include="Testably.Abstractions" />
    <PackageReference Include="ViciOne.Engine.DefaultPoolings" />
    <PackageReference Include="ViciOne.ManagedEngine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunicationProviders\CommunicationProviders.csproj" />
    <ProjectReference Include="..\PackageResolvers\PackageResolvers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ViciOne.EngineHost.EngineAssemblyLoadingTest" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="metadata.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
    <Content Update="packages.lock.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
  </ItemGroup>

</Project>
