<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViciOne.ManagedEngine.CommunicationContracts</AssemblyName>
    <RootNamespace>ViciOne.ManagedEngine.Communication</RootNamespace>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ViciOne.ManagedEngine.Contracts" />
  </ItemGroup>

</Project>
