<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet.Extensions.ManagedClient" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

</Project>
